declare module '*.css';
declare module '*.svg';
declare module 'swiper/css';
declare module 'swiper/css/navigation';
declare module 'swiper/css/effect-fade';
declare module 'swiper/css/effect-coverflow';
declare module 'react-google-recaptcha';
declare module '*.jsx';
declare module '../HomeComponent/MainComponent/Footer';
declare module '../../blueBerryComponents/HomeComponent/MainComponent/Footer';
declare module '../../blueBerryComponents/HomeComponent/MainComponent/Footer';
declare module '../../blueBerryComponents/HomeComponent/MainComponent/Footer.tsx/Footer';
declare module '../../firebase'