declare module '*.css';
declare module '*.svg';
declare module 'swiper/css';
declare module 'swiper/css/navigation';
declare module 'swiper/css/effect-fade';
declare module 'swiper/css/effect-coverflow';
declare module 'react-google-recaptcha';
declare module '*.jsx';
declare module '../HomeComponent/MainComponent/Footer';
declare module '../../blueBerryComponents/HomeComponent/MainComponent/Footer';
declare module '../../blueBerryComponents/HomeComponent/MainComponent/Footer';
declare module '../../blueBerryComponents/HomeComponent/MainComponent/Footer.tsx/Footer';
declare module '../../firebase'
declare module './Footer'
declare module '../firebase'
declare module '../HeaderComponent/Header.tsx/Header';
declare module '../HeaderComponent/NavComponet/Nav';
declare module '../HeaderComponent/FlatOfferComponent/FlatOffer';
declare module '../HeaderComponent/Header.tsx/Star.tsx';
declare module '../CartComponent/Cart';
declare module '../Loader/CakeLoading';
declare module '../Loader/DottedLoading';
declare module '../Loader/Loader';
declare module '../Loader/Loader.tsx';
declare module '../Loader/CakeLoading.tsx';
declare module '../Loader/DottedLoading.tsx';
declare module '../Loader/Loader.tsx/Loader';
declare module '../LoginComponent/Login';
declare module '../ProfileComponent/Profile';
declare module '../TrackOrder/TrackOrder';
declare module '../../../firebase'
declare module '../../../blueBerryComponents/HomeComponent/MainComponent/Footer';
declare module '../../../blueBerryComponents/HeaderComponent/Header.tsx/Header';
declare module '../../../blueBerryComponents/HeaderComponent/NavComponet/Nav';
declare module '../../../blueBerryComponents/HeaderComponent/FlatOfferComponent/FlatOffer';
declare module '../../../blueBerryComponents/HeaderComponent/Header.tsx/Star.tsx';
declare module '../../../blueBerryComponents/CartComponent/Cart';
declare module '../../../blueBerryComponents/Loader/CakeLoading';
declare module '../../../blueBerryComponents/Loader/DottedLoading';
